version: '3.4'

services:
  vibecheckserver:
    image: vibecheckserver
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:80"
    volumes:
      - .:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  vibecheck:
    image: vibecheck
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5001:80"
    volumes:
      - .:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development