version: '3.4'

services:
  vibecheckserver:
    image: vibecheckserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - .:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development